name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      # BaseHref sættes til "/" fordi du bruger custom domain (ikke repo-understi)
      - name: Publish Blazor WebAssembly app with correct BaseHref
        run: dotnet publish -c Release -o release -p:BaseHref=/ -p:StaticWebAssetBasePath=/

      # Klientruting på GitHub Pages
      - name: Copy index.html to 404.html (for client-side routing)
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      # Custom domain
      - name: Add CNAME file for custom domain
        run: echo "www.gametracker.hedef.dk" > release/wwwroot/CNAME

      # Slå Jekyll fra så _framework osv. ikke blokeres
      - name: Add .nojekyll
        run: touch release/wwwroot/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: release/wwwroot
          # valgfrit men ofte rart ved første deploy:
          # force_orphan: true
